using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assets.Scripts.HUD.DuelField
{
    enum TypeOfDuelAction
    {
        StartDuel,
        InitialDraw,
        InitialDrawP2,
        PAMulligan,
        PBMulligan,
        PBNoMulligan,
        PANoMulligan,
        PBMulliganF,
        PAMulliganF,
        DuelUpdate,
        ResetStep,
        ReSetStage,
        DrawPhase,
        DefeatedHoloMember,
        DefeatedHoloMemberByEffect,
        HolomemDefatedSoGainCheer,
        CheerStepEndDefeatedHolomem,
        CheerStep,
        CheerStepEnd,
        MainPhase,
        MainPhaseDoAction,
        Endturn,
        Endduel,
        AttachSupportItem,
        PlayHolomem,
        BloomHolomem,
        DoCollab,
        UnDoCollab,
        RemoveEnergyFrom,
        AttachEnergyResponse,
        PayHoloPowerCost,
        MoveCardToZone,
        DisposeUsedSupport,
        ResolveOnSupportEffect,
        OnCollabEffect,
        OnArtEffect,
        ResolveOnAttachEffect,
        ActiveArtEffect,
        PickFromListThenGiveBacKFromHandDone,
        RemoveCardsFromArquive,
        RemoveCardsFromHand,
        DrawOshiEffect,
        DrawBloomEffect,
        DrawBloomIncreaseEffect,
        DrawCollabEffect,
        DrawArtEffect,
        SupportEffectDraw,
        DrawAttachEffect,
        ShowCard,
        RollDice,
        OnlyDiceRoll,
        RecoverHolomem,
        InflicArtDamageToHolomem,
        InflicDamageToHolomem,
        InflicRecoilDamageToHolomem,
        SetHPToFixedValue,
        ResolveDamageToHolomem,
        SwitchStageCard,
        SwitchStageCardByRetreat,
        SwitchOpponentStageCard,
        RemoveEnergyAtAndDestroy,
        RemoveEnergyAtAndSendToArquive,
        RemoveEquipAtAndSendToArquive,
        SuffleDeck
    };
}
